// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_REGISTRATION MessageType = 0
	MessageType_USER_INPUT   MessageType = 1
	MessageType_OUTPUT       MessageType = 2
	MessageType_ERROR        MessageType = 3
	MessageType_REGISTERED   MessageType = 4
	MessageType_RESIZE       MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "REGISTRATION",
		1: "USER_INPUT",
		2: "OUTPUT",
		3: "ERROR",
		4: "REGISTERED",
		5: "RESIZE",
	}
	MessageType_value = map[string]int32{
		"REGISTRATION": 0,
		"USER_INPUT":   1,
		"OUTPUT":       2,
		"ERROR":        3,
		"REGISTERED":   4,
		"RESIZE":       5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type Role int32

const (
	Role_SHELL Role = 0
	Role_LLM   Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "SHELL",
		1: "LLM",
	}
	Role_value = map[string]int32{
		"SHELL": 0,
		"LLM":   1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Message_Registration
	//	*Message_UserInput
	//	*Message_Output
	//	*Message_Error
	//	*Message_Registered
	//	*Message_Resize
	Message       isMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_REGISTRATION
}

func (x *Message) GetMessage() isMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetRegistration() *RegistrationMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *Message) GetUserInput() *UserInputMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_UserInput); ok {
			return x.UserInput
		}
	}
	return nil
}

func (x *Message) GetOutput() *OutputMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *Message) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Message) GetRegistered() *RegisteredMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *Message) GetResize() *ResizeMessage {
	if x != nil {
		if x, ok := x.Message.(*Message_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_Registration struct {
	Registration *RegistrationMessage `protobuf:"bytes,10,opt,name=registration,proto3,oneof"`
}

type Message_UserInput struct {
	UserInput *UserInputMessage `protobuf:"bytes,11,opt,name=user_input,json=userInput,proto3,oneof"`
}

type Message_Output struct {
	Output *OutputMessage `protobuf:"bytes,12,opt,name=output,proto3,oneof"`
}

type Message_Error struct {
	Error *ErrorMessage `protobuf:"bytes,13,opt,name=error,proto3,oneof"`
}

type Message_Registered struct {
	Registered *RegisteredMessage `protobuf:"bytes,14,opt,name=registered,proto3,oneof"`
}

type Message_Resize struct {
	Resize *ResizeMessage `protobuf:"bytes,15,opt,name=resize,proto3,oneof"`
}

func (*Message_Registration) isMessage_Message() {}

func (*Message_UserInput) isMessage_Message() {}

func (*Message_Output) isMessage_Message() {}

func (*Message_Error) isMessage_Message() {}

func (*Message_Registered) isMessage_Message() {}

func (*Message_Resize) isMessage_Message() {}

type RegistrationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=Role" json:"role,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationMessage) Reset() {
	*x = RegistrationMessage{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationMessage) ProtoMessage() {}

func (x *RegistrationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationMessage.ProtoReflect.Descriptor instead.
func (*RegistrationMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationMessage) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *RegistrationMessage) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_SHELL
}

func (x *RegistrationMessage) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RegistrationMessage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type RegisteredMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxMessageSize uint32                 `protobuf:"varint,1,opt,name=max_message_size,json=maxMessageSize,proto3" json:"max_message_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisteredMessage) Reset() {
	*x = RegisteredMessage{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredMessage) ProtoMessage() {}

func (x *RegisteredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredMessage.ProtoReflect.Descriptor instead.
func (*RegisteredMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RegisteredMessage) GetMaxMessageSize() uint32 {
	if x != nil {
		return x.MaxMessageSize
	}
	return 0
}

type UserInputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInputMessage) Reset() {
	*x = UserInputMessage{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInputMessage) ProtoMessage() {}

func (x *UserInputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInputMessage.ProtoReflect.Descriptor instead.
func (*UserInputMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UserInputMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OutputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputMessage) Reset() {
	*x = OutputMessage{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputMessage) ProtoMessage() {}

func (x *OutputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputMessage.ProtoReflect.Descriptor instead.
func (*OutputMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *OutputMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResizeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeMessage) Reset() {
	*x = ResizeMessage{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeMessage) ProtoMessage() {}

func (x *ResizeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeMessage.ProtoReflect.Descriptor instead.
func (*ResizeMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ResizeMessage) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResizeMessage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\"\xd7\x02\n" +
	"\aMessage\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.MessageTypeR\x04type\x12:\n" +
	"\fregistration\x18\n" +
	" \x01(\v2\x14.RegistrationMessageH\x00R\fregistration\x122\n" +
	"\n" +
	"user_input\x18\v \x01(\v2\x11.UserInputMessageH\x00R\tuserInput\x12(\n" +
	"\x06output\x18\f \x01(\v2\x0e.OutputMessageH\x00R\x06output\x12%\n" +
	"\x05error\x18\r \x01(\v2\r.ErrorMessageH\x00R\x05error\x124\n" +
	"\n" +
	"registered\x18\x0e \x01(\v2\x12.RegisteredMessageH\x00R\n" +
	"registered\x12(\n" +
	"\x06resize\x18\x0f \x01(\v2\x0e.ResizeMessageH\x00R\x06resizeB\t\n" +
	"\amessage\"}\n" +
	"\x13RegistrationMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12\x19\n" +
	"\x04role\x18\x02 \x01(\x0e2\x05.RoleR\x04role\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\"=\n" +
	"\x11RegisteredMessage\x12(\n" +
	"\x10max_message_size\x18\x01 \x01(\rR\x0emaxMessageSize\"&\n" +
	"\x10UserInputMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"#\n" +
	"\rOutputMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"$\n" +
	"\fErrorMessage\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"=\n" +
	"\rResizeMessage\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height*b\n" +
	"\vMessageType\x12\x10\n" +
	"\fREGISTRATION\x10\x00\x12\x0e\n" +
	"\n" +
	"USER_INPUT\x10\x01\x12\n" +
	"\n" +
	"\x06OUTPUT\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\x0e\n" +
	"\n" +
	"REGISTERED\x10\x04\x12\n" +
	"\n" +
	"\x06RESIZE\x10\x05*\x1a\n" +
	"\x04Role\x12\t\n" +
	"\x05SHELL\x10\x00\x12\a\n" +
	"\x03LLM\x10\x01B\fZ\n" +
	"./messagesb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_messages_proto_goTypes = []any{
	(MessageType)(0),            // 0: MessageType
	(Role)(0),                   // 1: Role
	(*Message)(nil),             // 2: Message
	(*RegistrationMessage)(nil), // 3: RegistrationMessage
	(*RegisteredMessage)(nil),   // 4: RegisteredMessage
	(*UserInputMessage)(nil),    // 5: UserInputMessage
	(*OutputMessage)(nil),       // 6: OutputMessage
	(*ErrorMessage)(nil),        // 7: ErrorMessage
	(*ResizeMessage)(nil),       // 8: ResizeMessage
}
var file_messages_proto_depIdxs = []int32{
	0, // 0: Message.type:type_name -> MessageType
	3, // 1: Message.registration:type_name -> RegistrationMessage
	5, // 2: Message.user_input:type_name -> UserInputMessage
	6, // 3: Message.output:type_name -> OutputMessage
	7, // 4: Message.error:type_name -> ErrorMessage
	4, // 5: Message.registered:type_name -> RegisteredMessage
	8, // 6: Message.resize:type_name -> ResizeMessage
	1, // 7: RegistrationMessage.role:type_name -> Role
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Registration)(nil),
		(*Message_UserInput)(nil),
		(*Message_Output)(nil),
		(*Message_Error)(nil),
		(*Message_Registered)(nil),
		(*Message_Resize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
